version: '3.9'

services:
  django:
    image: django-docker:0.0.1
    command: python manage.py runserver 0.0.0.0:8000    
    volumes:      
      - .:/EXECL_FILE_UPLOAD
    build: .
    ports:
      - "8000:8000"

